apiVersion: v1
kind: LimitRange
metadata:
  name: ml-workshop-limit-range
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: '1'
    defaultRequest:
      memory: 50Mi
      cpu: 50m
    type: Container
